#!/bin/bash

# 设置脚本执行时的错误处理
set -e
set -o pipefail

# 显示使用方法
show_usage() {
    echo "用法: $0 -p <搜索路径> [选项]"
    echo "选项:"
    echo "  -p <路径>              指定要递归搜索的路径（必需）"
    echo "  -o, --output <文件名>   指定输出文件名（默认：Dialects.td）"
    echo "  -h, --help             显示此帮助信息"
    echo
    echo "示例:"
    echo "  $0 -p /path/to/search"
    echo "  $0 -p /path/to/search -o CustomDialects.td"
}

# 默认值设置
OUTPUT_FILE="Dialects.td"
TEMP_FILE="temp_dialects.td"
LOG_DIR="td_logs"
LOG_FILE="${LOG_DIR}/combine_dialects_$(date '+%Y%m%d_%H%M%S').log"
SEARCH_PATH=""

# 创建日志目录
mkdir -p "$LOG_DIR"

# 解析命令行参数
while [[ $# -gt 0 ]]; do
    case $1 in
        -p)
            if [ -n "$2" ]; then
                SEARCH_PATH="$2"
                shift 2
            else
                echo "错误：-p 参数需要指定路径"
                show_usage
                exit 1
            fi
            ;;
        -o|--output)
            if [ -n "$2" ]; then
                OUTPUT_FILE="$2"
                shift 2
            else
                echo "错误：-o 参数需要指定输出文件名"
                show_usage
                exit 1
            fi
            ;;
        -h|--help)
            show_usage
            exit 0
            ;;
        *)
            echo "错误：未知参数 $1"
            show_usage
            exit 1
            ;;
    esac
done

# 验证是否提供了搜索路径
if [ -z "$SEARCH_PATH" ]; then
    echo "错误：必须使用 -p 参数指定搜索路径"
    show_usage
    exit 1
fi

# 验证搜索路径是否存在
if [ ! -d "$SEARCH_PATH" ]; then
    echo "错误：搜索路径 '$SEARCH_PATH' 不存在或不是一个目录"
    exit 1
fi

# 日志函数
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

cleanup() {
    if [ -f "$TEMP_FILE" ]; then
        rm -f "$TEMP_FILE"
        log "清理临时文件"
    fi
}

# 注册清理函数
trap cleanup EXIT

log "开始执行文件合并任务"
log "搜索路径: $SEARCH_PATH"
log "输出文件: $OUTPUT_FILE"
log "日志文件: $LOG_FILE"

# 检查是否存在旧的输出文件
if [ -f "$OUTPUT_FILE" ]; then
    log "发现已存在的 $OUTPUT_FILE 文件，将其备份"
    mv "$OUTPUT_FILE" "${OUTPUT_FILE}.bak"
fi

# 添加文件头
cat > "$TEMP_FILE" << 'EOL'
//===- Dialects.td - Dialect definitions ---------------------*- tablegen -*-===//
//
// This file is auto-generated by combine_dialects.sh
//
//===----------------------------------------------------------------------===//

EOL

# 查找所有 *Dialect.td 文件和与文件夹同名的 .td 文件
log "开始搜索 Dialect 文件"
found_files=""

# 首先查找所有 *Dialect.td 文件
dialect_files=$(find "$SEARCH_PATH" -name "*Dialect.td" -not -path "*/\.*" | sort)

# 然后查找与文件夹同名的 .td 文件
while IFS= read -r dir; do
    if [ -d "$dir" ]; then
        dirname=$(basename "$dir")
        td_file="$dir/$dirname.td"
        if [ -f "$td_file" ]; then
            found_files+="$td_file"$'\n'
        fi
    fi
done < <(find "$SEARCH_PATH" -type d -not -path "*/\.*")

# 合并两种文件的列表并排序
found_files=$(echo -e "${dialect_files}\n${found_files}" | sort | grep -v "^$")

if [ -z "$found_files" ]; then
    log "错误：在路径 '$SEARCH_PATH' 下未找到任何有效的 Dialect 文件"
    exit 1
fi

# 记录找到的文件数量
file_count=$(echo "$found_files" | wc -l)
log "找到 $file_count 个 Dialect 文件"

# 创建一个临时文件来存储已处理的文件名，避免重复处理
processed_files=$(mktemp)

# 遍历所有找到的文件并合并
while IFS= read -r file; do
    filename=$(basename "$file")
    if [ -f "$file" ]; then
        # 检查是否已经处理过这个文件
        if ! grep -q "$filename" "$processed_files"; then
            log "处理文件: $file"
            echo "// Including content from: $file" >> "$TEMP_FILE"
            cat "$file" >> "$TEMP_FILE"
            echo -e "\n" >> "$TEMP_FILE"
            echo "$filename" >> "$processed_files"
        fi
    else
        log "警告：文件 $file 无法访问，已跳过"
    fi
done <<< "$found_files"

# 删除临时文件
rm "$processed_files"

# 添加文件尾
cat >> "$TEMP_FILE" << 'EOL'

//===----------------------------------------------------------------------===//
// End of auto-generated file
//===----------------------------------------------------------------------===//
EOL

# 移动临时文件到最终位置
mv "$TEMP_FILE" "$OUTPUT_FILE"
log "完成！输出文件已保存为: $OUTPUT_FILE"

# 显示处理结果的统计信息
total_lines=$(wc -l < "$OUTPUT_FILE")
log "统计信息:"
log "- 合并的文件数: $file_count"
log "- 总行数: $total_lines"

# 在日志结尾添加分隔线
echo -e "\n----------------------------------------\n" >> "$LOG_FILE"

exit 0