dialects:

  fake:
    passes:
      - name: "print-op-stats{json}"
        description: "Print statistics of operations"
        type: MODULE
        next_pass: null

  builtin:
    description: "The builtin dialect contains a core set of Attributes, Operations, and Types that have wide applicability across a very large number of domains and abstractions."
    passes:
      - name: "reconcile-unrealized-casts"
        description: "Simplify and eliminate unrealized conversion casts"
        type: MODULE
        next_pass: null


  affine:
    description: "Affine dialect for loop transformations"
    passes:
      - name: "lower-affine"
        description: "Lower Affine operations to a combination of Standard and SCF operations"
        next_pass: null

  vector:
    description: "Vector dialect for SIMD operations"
    passes:
      - name: "convert-vector-to-scf"
        description: "Convert Vector dialect to SCF dialect"
        next_pass: 'lower-affine'
      - name: "convert-vector-to-llvm"
        description: "Convert Vector dialect directly to LLVM dialect"
        next_pass: null

  arith:
    description: "Arithmetic operations dialect"
    passes:
      - name: "convert-arith-to-llvm"
        description: "Convert Arith dialect to LLVM dialect"
        next_pass: null
      - name: "arith-expand"
        description: "Legalize Arith ops to be convertible to LLVM."
        next_pass: "convert-arith-to-llvm"

  math:
    description: "The math dialect is intended to hold mathematical operations on integer and floating types beyond simple arithmetics. "
    passes:
      - name: "convert-math-to-llvm"
        description: "Convert Math dialect to LLVM dialect"
        next_pass: null
      - name: "convert-math-to-libm"

  tosa:
    description: "Tensor Operator Set Architecture dialect"
    passes:
      - name: "tosa-to-linalg"
        type: FUNC
        description: "Lower TOSA to LinAlg on tensors"
        next_pass: null
      - name: "tosa-to-arith"
        type: FUNC
        description: "Lower TOSA to the Arith dialect"
        next_pass: null
      - name: "tosa-to-linalg-named"
        type: FUNC
        description: "Lower TOSA to LinAlg named operations"
        next_pass: null 
      - name: "tosa-to-tensor"
        type: FUNC
        description: "Lower TOSA to the Tensor dialect"
        next_pass: null
      - name: tosa-to-linalg-pipeline
      - name: tosa-to-mlprogram
      - name: tosa-to-scf
        type: FUNC

  linalg:
    description: "Linear algebra operations dialect"
    passes:
      - name: "convert-linalg-to-loops"
        description: "Lowers the linalg ops to loop nests using scf.for."
        next_pass: null
      - name: "convert-linalg-to-affine-loops"
        description: "Lower the operations from the linalg dialect into affine loops"
        next_pass: null
      - name: "convert-linalg-to-parallel-loops"
        description: "Lower the operations from the linalg dialect into parallel loops"
        next_pass: null

  scf:
    description: "Structured Control Flow dialect"
    passes:
      - name: "convert-scf-to-cf"
        description: "Convert SCF dialect to ControlFlow dialect, replacing structured control flow with a CFG"
        next_pass: null

  cf:
    description: "Control Flow dialect"
    passes:
      - name: "convert-cf-to-llvm"
        description: "Convert ControlFlow operations to the LLVM dialect"
        next_pass: null

  func:
    description: "Function operations dialect"
    passes:
      - name: "convert-func-to-llvm"
        description: "Convert from the Func dialect to the LLVM dialect"
        next_pass: null

  memref:
    description: "Memory Reference dialect"
    passes:
      - name: "finalize-memref-to-llvm"
        description: "Finalize MemRef dialect to LLVM dialect conversion"
        next_pass: null
      - name: "expand-strided-metadata"
        description: "Expand memref operations into easier to analyze constructs"
        next_pass: "lower-affine"
  
  llvm:
    description: "llvm dialect"


  tensor:
    description: "Tensor operations dialect"
    passes:
      - name: "one-shot-bufferize{bufferize-function-boundaries}"
        description: "Bufferize Tensor operations"
        next_pass: null
      - name: "one-shot-bufferize{unknown-type-conversion=fully-dynamic-layout-map}"
        description: "Bufferize tensor.cast op"
        next_pass: null
      - name: convert-tensor-to-linalg


  bufferization:
    description: "Bufferization dialect for memory management"
    passes:
      - name: "buffer-deallocation-pipeline"
        description: "Handle buffer deallocation for memory optimization"
        next_pass: null

  ml_program:
    description: "Bufferization dialect for memory management"
    passes:
      - name: "mlprogram-pipeline-globals"
        type: FUNC
        description: "Handle buffer deallocation for memory optimization"
        next_pass: null

  shape: 
    passes:
      - name: "convert-shape-constraints"
      - name: "convert-shape-to-std"

  complex:
    description: ""
    passes:
      - name: "convert-complex-to-libm"
      - name: "convert-complex-to-llvm"
      - name: convert-complex-to-standard

  index:
    description: ""
    passes:
      - name: "convert-index-to-llvm"

pipelines:
  tosa-to-llvm:
    stages:
      - name: "Torch"
        execute: "torch"

      - name: "Torch Conversion"
        execute: "torch_c"

      - name: "TOSA Conversion"
        execute: "tosa"
        
      - name: "Tensor Bufferization"
        execute: "tensor"
        
      - name: "Bufferization deallocation"
        execute: "bufferization"

      - name: "Linalg Conversion"
        execute: "linalg"

      - name: "Affine Conversion"
        execute: "affine"

      - name: "Conversion to LLVM"
        execute: null
